name: 'Lint Code'

on:
  push:
    branches: [main, master]  # Add dev here if needed
  pull_request:
    branches: [main, master]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Debug: List files
        run: ls -R

      - name: Run Python Linter
        run: |
          echo "Running flake8..."
          find . -name "*.py" -exec flake8 {} +
          echo "✅ Linted all Python files successfully"

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install JSHint
        run: npm install --global jshint

      - name: Debug: List files
        run: ls -R

      - name: Run JavaScript Linter
        run: |
          echo "Running JSHint..."
          find . -name "*.js" -exec jshint {} +
          echo "✅ Linted all JS files successfully"
