name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Create flake8 config
      run: |
        echo "[flake8]" > .flake8
        echo "max-line-length = 88" >> .flake8
        echo "exclude = .git,__pycache__,env,venv" >> .flake8

    - name: Run flake8
      run: |
        echo "Running flake8..."
        flake8 . --count --select=E,F,W --show-source --statistics
        echo "✅ Python linting completed."
      continue-on-error: false

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install JSHint
      run: npm install jshint --global

    - name: Create JSHint config
      run: |
        echo '{
          "esversion": 8
        }' > .jshintrc

    - name: Run JSHint
      run: |
        echo "Running jshint..."
        jshint . || exit 1
        echo "✅ JavaScript linting completed."
